default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chats_development
  host: localhost
  port: 5432
  database: kopilka_prod
  username: kopilka_rec
  password: dkvs43gh4

test: 
  <<: *default
  database: chats_test
  username: kopilka_rec
  password: dkvs43gh4
  host: localhost
  port: 5432

production:
  <<: *default
  database: chats_production
  username: chats
  password: <%= ENV['CHATS_DATABASE_PASSWORD'] %>
