default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dba
  username: kopilka_rec
  password: dkvs43gh4
  host: localhost
  port: 5432

test:
  <<: *default
  database: dba_test
  username: kopilka_rec
  password: dkvs43gh4
  host: localhost
  port: 5432

production:
  <<: *default
  database: dba_prod
  username: kopilka_rec
  password: <%= ENV['CHATS_DATABASE_PASSWORD'] %>
